// Tipos de incidente SCI con schema dinámico de campos
// `fields` describe inputs del formulario; `defaultZones` en metros (rojo/amarillo/verde).

export const SCI_INCIDENT_TYPES = {
  sismo: {
    key: 'sismo',
    label: 'Sismo',
    icon: '🌐',
    color: '#a78bfa',
    esfTags: ['ESF-9', 'ESF-8', 'ESF-3'],
    requiredResponders: ['BOMBEROS', 'PC', 'CRUZROJA', 'ERUM', 'SEDENA'],
    defaultZones: { red: 800, yellow: 2000, green: 4000 },
    fields: [
      { name: 'magnitud',          label: 'Magnitud (Richter)',   type: 'range',  min: 3, max: 9, step: 0.1, default: 6.5 },
      { name: 'profundidad',       label: 'Profundidad (km)',     type: 'number', min: 1, max: 700, default: 35 },
      { name: 'intensidadMercalli',label: 'Intensidad Mercalli',  type: 'select',
        options: ['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII'], default: 'VI' },
      { name: 'tsunami',           label: 'Alerta tsunami',       type: 'select', options: ['No','Sí','Vigilancia'], default: 'No' },
      { name: 'replicas',          label: 'Réplicas registradas', type: 'number', min: 0, max: 999, default: 0 },
      { name: 'epicentroLat', label: 'Epicentro lat',     type: 'number', step: 0.0001, default: null, hint: 'Default: punto seleccionado' },
      { name: 'epicentroLng', label: 'Epicentro lng',     type: 'number', step: 0.0001, default: null },
    ],
  },
  colapso: {
    key: 'colapso',
    label: 'Colapso de estructura',
    icon: '🏚️',
    color: '#f97316',
    esfTags: ['ESF-9', 'ESF-8', 'ESF-3'],
    requiredResponders: ['BOMBEROS', 'PC', 'ERUM', 'CRUZROJA'],
    defaultZones: { red: 80, yellow: 200, green: 500 },
    fields: [
      { name: 'tipoEdificio', label: 'Tipo de inmueble', type: 'select', options: [
        'Habitacional', 'Comercial', 'Educativo', 'Industrial', 'Mixto', 'Patrimonial',
      ], default: 'Habitacional' },
      { name: 'pisos',     label: 'Pisos',              type: 'number', min: 1, max: 60, default: 4 },
      { name: 'atrapados', label: 'Atrapados estimados', type: 'number', min: 0, max: 500, default: 5 },
    ],
  },
  incendio: {
    key: 'incendio',
    label: 'Incendio estructural',
    icon: '🔥',
    color: '#fb923c',
    esfTags: ['ESF-4', 'ESF-8'],
    requiredResponders: ['BOMBEROS', 'ERUM'],
    defaultZones: { red: 60, yellow: 150, green: 400 },
    fields: [
      { name: 'descripcion', label: 'Descripción',  type: 'textarea', default: '' },
      { name: 'victimas',    label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas',         type: 'textarea', default: '' },
    ],
  },
  vial: {
    key: 'vial',
    label: 'Accidente vial masivo',
    icon: '🚗',
    color: '#fbbf24',
    esfTags: ['ESF-1', 'ESF-8', 'ESF-13'],
    requiredResponders: ['SSC', 'ERUM', 'CRUZROJA'],
    defaultZones: { red: 50, yellow: 150, green: 350 },
    fields: [
      { name: 'descripcion', label: 'Descripción', type: 'textarea', default: '' },
      { name: 'victimas',    label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas', type: 'textarea', default: '' },
    ],
  },
  hazmat: {
    key: 'hazmat',
    label: 'HAZMAT / Materiales peligrosos',
    icon: '☣️',
    color: '#facc15',
    esfTags: ['ESF-10', 'ESF-8', 'ESF-13'],
    requiredResponders: ['BOMBEROS', 'PC', 'SEDENA'],
    defaultZones: { red: 150, yellow: 500, green: 1500 },
    fields: [
      { name: 'descripcion', label: 'Descripción', type: 'textarea', default: '' },
      { name: 'victimas',    label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas', type: 'textarea', default: '' },
    ],
  },
  inundacion: {
    key: 'inundacion',
    label: 'Inundación',
    icon: '🌊',
    color: '#0ea5e9',
    esfTags: ['ESF-9', 'ESF-6', 'ESF-3'],
    requiredResponders: ['BOMBEROS', 'PC', 'SEDENA'],
    defaultZones: { red: 200, yellow: 600, green: 1500 },
    fields: [
      { name: 'descripcion', label: 'Descripción', type: 'textarea', default: '' },
      { name: 'victimas',    label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas', type: 'textarea', default: '' },
    ],
  },
  explosion: {
    key: 'explosion',
    label: 'Explosión',
    icon: '💥',
    color: '#ef4444',
    esfTags: ['ESF-4', 'ESF-8', 'ESF-13'],
    requiredResponders: ['BOMBEROS', 'ERUM', 'PC', 'CRUZROJA'],
    defaultZones: { red: 200, yellow: 500, green: 1200 },
    fields: [
      { name: 'descripcion', label: 'Descripción', type: 'textarea', default: '' },
      { name: 'victimas',    label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas', type: 'textarea', default: '' },
    ],
  },
  fugaQuimica: {
    key: 'fugaQuimica',
    label: 'Fuga química',
    icon: '⚗️',
    color: '#10b981',
    esfTags: ['ESF-10', 'ESF-8'],
    requiredResponders: ['BOMBEROS', 'PC'],
    defaultZones: { red: 120, yellow: 400, green: 1000 },
    fields: [
      { name: 'descripcion', label: 'Descripción', type: 'textarea', default: '' },
      { name: 'victimas',    label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas', type: 'textarea', default: '' },
    ],
  },
  seguridad: {
    key: 'seguridad',
    label: 'Seguridad pública',
    icon: '🚨',
    color: '#38bdf8',
    esfTags: ['ESF-13', 'ESF-5'],
    requiredResponders: ['SSC'],
    defaultZones: { red: 80, yellow: 200, green: 500 },
    fields: [
      { name: 'descripcion', label: 'Descripción', type: 'textarea', default: '' },
      { name: 'victimas',    label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas', type: 'textarea', default: '' },
    ],
  },
  tsunami: {
    key: 'tsunami',
    label: 'Tsunami / Maremoto',
    icon: '🌊',
    color: '#0284c7',
    esfTags: ['ESF-9', 'ESF-6', 'ESF-8'],
    requiredResponders: ['BOMBEROS', 'PC', 'SEDENA', 'MARINA', 'ERUM'],
    defaultZones: { red: 2000, yellow: 5000, green: 10000 },
    fields: [
      { name: 'alturaOla',    label: 'Altura ola est. (m)', type: 'number', min: 0.5, max: 40, step: 0.5, default: 5 },
      { name: 'velocidad',    label: 'Velocidad (km/h)',    type: 'number', min: 10,  max: 900, default: 700 },
      { name: 'alertaTemprana', label: 'Alerta temprana',  type: 'select', options: ['Sí', 'No', 'Parcial'], default: 'No' },
      { name: 'victimas',     label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
    ],
  },
  fallaElectrica: {
    key: 'fallaElectrica',
    label: 'Falla eléctrica masiva',
    icon: '⚡',
    color: '#fde047',
    esfTags: ['ESF-12', 'ESF-2', 'ESF-5'],
    requiredResponders: ['CFE', 'C5', 'SEMOVI', 'SSC'],
    defaultZones: { red: 500, yellow: 2000, green: 8000 },
    fields: [
      { name: 'coloniaAfectada', label: 'Zona afectada',    type: 'textarea', default: '' },
      { name: 'usrAfectados',    label: 'Usuarios afect.',  type: 'number', min: 0, default: 1000 },
      { name: 'tipoFalla',       label: 'Tipo de falla',    type: 'select',
        options: ['Subestación', 'Línea de transmisión', 'Vandalismo', 'Cortocircuito', 'Otro'], default: 'Subestación' },
      { name: 'hospitalesAfect', label: 'Hospitales afect.',type: 'number', min: 0, default: 0 },
    ],
  },
  hundimiento: {
    key: 'hundimiento',
    label: 'Hundimiento / Socavón',
    icon: '🕳️',
    color: '#78716c',
    esfTags: ['ESF-3', 'ESF-9', 'ESF-1'],
    requiredResponders: ['BOMBEROS', 'PC', 'SACMEX', 'SEDENA'],
    defaultZones: { red: 100, yellow: 300, green: 700 },
    fields: [
      { name: 'diametro',    label: 'Diámetro aprox. (m)', type: 'number', min: 1, max: 200, default: 10 },
      { name: 'profundidad', label: 'Profundidad (m)',      type: 'number', min: 1, max: 50,  default: 5 },
      { name: 'causa',       label: 'Causa probable',       type: 'select',
        options: ['Fuga de agua', 'Fuga de gas', 'Minería', 'Subsidencia natural', 'Indeterminada'], default: 'Fuga de agua' },
      { name: 'vehAtrap',    label: 'Vehículos atrapados',  type: 'number', min: 0, default: 0 },
      { name: 'victimas',    label: 'Víctimas estimadas',   type: 'number', min: 0, default: 0 },
    ],
  },
  inundacionPluvial: {
    key: 'inundacionPluvial',
    label: 'Inundación pluvial',
    icon: '🌧️',
    color: '#60a5fa',
    esfTags: ['ESF-3', 'ESF-6', 'ESF-1'],
    requiredResponders: ['BOMBEROS', 'PC', 'SACMEX', 'SEMOVI'],
    defaultZones: { red: 300, yellow: 1000, green: 3000 },
    fields: [
      { name: 'nivelAgua',   label: 'Nivel agua (cm)',     type: 'number', min: 0, max: 500, default: 40 },
      { name: 'alcaldia',    label: 'Alcaldía',            type: 'textarea', default: '' },
      { name: 'vialidades',  label: 'Vialidades bloqueadas', type: 'number', min: 0, default: 0 },
      { name: 'victimas',    label: 'Personas afectadas',  type: 'number', min: 0, default: 0 },
    ],
  },
  disturbio: {
    key: 'disturbio',
    label: 'Disturbio civil / Protesta',
    icon: '📢',
    color: '#f472b6',
    esfTags: ['ESF-13', 'ESF-15', 'ESF-5'],
    requiredResponders: ['SSC', 'C5'],
    defaultZones: { red: 150, yellow: 400, green: 1000 },
    fields: [
      { name: 'personasEst', label: 'Personas estimadas',  type: 'number', min: 0, default: 200 },
      { name: 'nivel',       label: 'Nivel de conflicto',  type: 'select',
        options: ['Bajo', 'Moderado', 'Alto', 'Crítico'], default: 'Moderado' },
      { name: 'vialBloq',    label: 'Vialidades bloqueadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas',               type: 'textarea', default: '' },
    ],
  },
  // ── Tipos adicionales NIMS/ICS ──
  rescate: {
    key: 'rescate',
    label: 'Búsqueda y Rescate (SAR)',
    icon: '🔦',
    color: '#34d399',
    esfTags: ['ESF-9', 'ESF-8'],
    requiredResponders: ['BOMBEROS', 'PC', 'ERUM', 'SEDENA'],
    defaultZones: { red: 100, yellow: 300, green: 800 },
    fields: [
      { name: 'tipoRescate', label: 'Tipo de rescate', type: 'select',
        options: ['Estructural', 'Acuático', 'Montaña', 'Vehicular', 'Confinado', 'Otro'], default: 'Estructural' },
      { name: 'atrapados',   label: 'Personas atrapadas', type: 'number', min: 0, default: 1 },
      { name: 'victimas',    label: 'Víctimas estimadas', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas',              type: 'textarea', default: '' },
    ],
  },
  incendioForestal: {
    key: 'incendioForestal',
    label: 'Incendio forestal / Wildland',
    icon: '🌲',
    color: '#f97316',
    esfTags: ['ESF-4', 'ESF-9', 'ESF-11'],
    requiredResponders: ['BOMBEROS', 'PC', 'SEDENA', 'CONAFOR'],
    defaultZones: { red: 500, yellow: 1500, green: 4000 },
    fields: [
      { name: 'hectareas',    label: 'Hectáreas estimadas', type: 'number', min: 0, default: 10 },
      { name: 'tipoVegetacion', label: 'Tipo de vegetación', type: 'select',
        options: ['Pastizal', 'Matorral', 'Bosque templado', 'Selva', 'Mezclado'], default: 'Matorral' },
      { name: 'viento',       label: 'Viento (km/h)',      type: 'number', min: 0, max: 150, default: 20 },
      { name: 'victimas',     label: 'Personas afectadas', type: 'number', min: 0, default: 0 },
    ],
  },
  emergenciaMedica: {
    key: 'emergenciaMedica',
    label: 'Emergencia médica masiva (MCI)',
    icon: '🏥',
    color: '#f43f5e',
    esfTags: ['ESF-8', 'ESF-6'],
    requiredResponders: ['ERUM', 'CRUZROJA', 'IMSS', 'SEDENA'],
    defaultZones: { red: 100, yellow: 300, green: 800 },
    fields: [
      { name: 'causaMCI',  label: 'Causa del MCI', type: 'select',
        options: ['Intoxicación masiva', 'Colapso masivo', 'Traumatismo masivo', 'Epidemia/brote', 'Otro'], default: 'Traumatismo masivo' },
      { name: 'victimas',  label: 'Víctimas estimadas', type: 'number', min: 0, default: 10 },
      { name: 'criticos',  label: 'Críticos (Rojo START)', type: 'number', min: 0, default: 0 },
      { name: 'hopSoporte',label: 'Hospitales de soporte', type: 'number', min: 0, default: 1 },
    ],
  },
  evacuacion: {
    key: 'evacuacion',
    label: 'Evacuación masiva',
    icon: '🚶',
    color: '#818cf8',
    esfTags: ['ESF-6', 'ESF-1', 'ESF-13'],
    requiredResponders: ['PC', 'SSC', 'SEDENA', 'SEMOVI'],
    defaultZones: { red: 500, yellow: 2000, green: 8000 },
    fields: [
      { name: 'causaEvac',   label: 'Causa de evacuación', type: 'select',
        options: ['Sismo', 'Inundación', 'HAZMAT', 'Incendio', 'Amenaza', 'Otro'], default: 'Sismo' },
      { name: 'personasEvac',label: 'Personas a evacuar', type: 'number', min: 0, default: 500 },
      { name: 'albergues',   label: 'Albergues activados', type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Rutas de evacuación', type: 'textarea', default: '' },
    ],
  },
  otro: {
    key: 'otro',
    label: 'Otro / No clasificado',
    icon: '⚠️',
    color: '#94a3b8',
    esfTags: ['ESF-5'],
    requiredResponders: ['PC'],
    defaultZones: { red: 100, yellow: 300, green: 800 },
    fields: [
      { name: 'descripcion', label: 'Descripción del incidente', type: 'textarea', default: '' },
      { name: 'victimas',    label: 'Víctimas estimadas',        type: 'number', min: 0, default: 0 },
      { name: 'notas',       label: 'Notas adicionales',         type: 'textarea', default: '' },
    ],
  },
}

export const INCIDENT_TYPE_KEYS = Object.keys(SCI_INCIDENT_TYPES)
export const incidentType = (key) => SCI_INCIDENT_TYPES[key]
