// Plantillas fijas de personal y equipo por typeCode (no random)
// Cada Resource tiene un typeCode que mapea aquí.

export const UNIT_TEMPLATES = {
  'ambulancia-basica': {
    label: 'Ambulancia Básica (SVB)',
    descripcion: 'Ambulancia de Soporte Vital Básico para atención prehospitalaria.',
    capacidad: '1 paciente en camilla + 1 sentado',
    personal: [
      { rango: 'TUM-B', rol: 'Técnico en Urgencias Médicas (responsable)' },
      { rango: 'TUM-B', rol: 'Asistente / Conductor' },
    ],
    equipo: [
      'Camilla principal rígida',
      'DEA (desfibrilador externo automático)',
      'Tanque oxígeno portátil 625 L + mascarillas',
      'Botiquín ABC + collarín cervical',
      'Férulas neumáticas y rígidas',
      'Kit obstétrico',
      'Radio P25 interoperable',
    ],
  },
  'ambulancia-intensiva': {
    label: 'Ambulancia Intensiva (SVA)',
    descripcion: 'Ambulancia de Soporte Vital Avanzado con equipamiento de cuidados intensivos.',
    capacidad: '1 paciente crítico + 2 acompañantes',
    personal: [
      { rango: 'Médico', rol: 'Médico de urgencias (responsable)' },
      { rango: 'TUM-A', rol: 'Técnico en Urgencias Avanzado' },
      { rango: 'TUM-B', rol: 'Conductor / Asistente' },
    ],
    equipo: [
      'Monitor desfibrilador manual con marcapasos',
      'Ventilador de transporte',
      'Bomba de infusión doble canal',
      'Capnógrafo + glucómetro',
      'Maletín ALS (intubación, vía aérea avanzada)',
      'Carro de medicamentos (>40 fármacos)',
      'Camilla con sistema de cargador hidráulico',
      'Radio P25',
    ],
  },
  'rescate-erum': {
    label: 'Unidad de Rescate ERUM',
    descripcion: 'Vehículo de rescate vehicular y rescate técnico.',
    capacidad: '4 rescatistas + víctima',
    personal: [
      { rango: 'Comandante', rol: 'Jefe de unidad' },
      { rango: 'Rescatista', rol: 'Operador hidráulico' },
      { rango: 'Rescatista', rol: 'Soporte / cabos' },
      { rango: 'TUM-A',      rol: 'Atención prehospitalaria' },
    ],
    equipo: [
      'Equipo hidráulico Holmatro (cizalla, separador, ariete)',
      'Generador eléctrico portátil',
      'Set de calzas y cuñas',
      'Cuerdas dinámicas + arneses (rescate vertical)',
      'Camilla canasta tipo Stokes',
      'Maletín de trauma',
    ],
  },
  'patrulla-ssc': {
    label: 'Patrulla SSC',
    descripcion: 'Unidad de patrullaje preventivo y reactivo.',
    capacidad: '2 oficiales + 2 detenidos',
    personal: [
      { rango: 'Suboficial', rol: 'Responsable de patrulla' },
      { rango: 'Policía',    rol: 'Conductor' },
    ],
    equipo: [
      'Radio matra P25',
      'Chalecos balísticos nivel III-A',
      'Arma corta reglamentaria',
      'Esposas / sujeción',
      'Cámara corporal',
      'Botiquín de primeros auxilios',
    ],
  },
  'k9-ssc': {
    label: 'Unidad K9',
    descripcion: 'Unidad canina de búsqueda, detección y rescate.',
    capacidad: '2 oficiales + 1 binomio canino',
    personal: [
      { rango: 'Oficial guía', rol: 'Manejador K9' },
      { rango: 'Policía',      rol: 'Apoyo / conductor' },
      { rango: 'K9',           rol: 'Binomio canino entrenado' },
    ],
    equipo: [
      'Equipo de adiestramiento',
      'Arnés y correa de trabajo',
      'Detector portátil',
      'Botiquín veterinario',
      'Radio P25',
    ],
  },
  'rescate-bomberos': {
    label: 'Camión de Rescate Bomberos',
    descripcion: 'Unidad de combate de incendio estructural y rescate.',
    capacidad: '6 bomberos + equipo pesado',
    personal: [
      { rango: 'Capitán',   rol: 'Comandante de incidente' },
      { rango: 'Teniente',  rol: 'Jefe de pelotón' },
      { rango: 'Bombero',   rol: 'Atacante de línea' },
      { rango: 'Bombero',   rol: 'Atacante de línea' },
      { rango: 'Bombero',   rol: 'Operador de bomba' },
      { rango: 'Bombero',   rol: 'Apoyo / ventilación' },
    ],
    equipo: [
      'Bomba 1500 GPM',
      'Tanque 500 galones',
      'Mangueras 1.5" y 2.5"',
      'SCBA × 6 (autocontenidos)',
      'Equipo TIC (cámara térmica)',
      'Equipo hidráulico de extracción',
      'Cuerdas y arneses',
    ],
  },
  'pipa-bomberos': {
    label: 'Pipa de Agua',
    descripcion: 'Vehículo cisterna de apoyo logístico de agua.',
    capacidad: '3 000 galones',
    personal: [
      { rango: 'Bombero', rol: 'Operador' },
      { rango: 'Bombero', rol: 'Apoyo' },
    ],
    equipo: [
      'Tanque 3 000 gal',
      'Bomba portátil',
      'Mangueras de succión',
      'Radio',
    ],
  },
  'pc-busqueda-rescate': {
    label: 'USAR Protección Civil',
    descripcion: 'Unidad de Búsqueda y Rescate Urbano de PC CDMX.',
    capacidad: '8 elementos + binomios K9',
    personal: [
      { rango: 'Coordinador', rol: 'Jefe de equipo USAR' },
      { rango: 'Rescatista',  rol: 'Búsqueda técnica' },
      { rango: 'Rescatista',  rol: 'Búsqueda técnica' },
      { rango: 'Rescatista',  rol: 'Apoyo logístico' },
      { rango: 'Médico',      rol: 'Atención médica' },
      { rango: 'K9',          rol: 'Binomio canino' },
    ],
    equipo: [
      'Cámaras de búsqueda (snake / borescope)',
      'Geófonos sísmicos',
      'Cortadoras de concreto',
      'Apuntalamientos de madera',
      'Sistema de comunicación in-situ',
      'Botiquín de trauma',
    ],
  },
  'pc-evaluacion': {
    label: 'Unidad PC Evaluación',
    descripcion: 'Camioneta de evaluación estructural y coordinación.',
    capacidad: '4 evaluadores + equipo',
    personal: [
      { rango: 'Ing. Civil', rol: 'Evaluador estructural' },
      { rango: 'Coord. PC',  rol: 'Enlace con C5' },
      { rango: 'Operador',   rol: 'Conductor' },
    ],
    equipo: [
      'Drone con cámara térmica',
      'Distanciómetro láser',
      'Cuestionarios ATC-20',
      'Radio HF/VHF',
      'Cintas y señalización',
    ],
  },
  'cruzroja-basica': {
    label: 'Ambulancia Cruz Roja Básica',
    descripcion: 'Ambulancia voluntaria SVB de Cruz Roja Mexicana.',
    capacidad: '1 paciente + 1 acompañante',
    personal: [
      { rango: 'TUM-B', rol: 'Socorrista responsable' },
      { rango: 'TUM-B', rol: 'Conductor socorrista' },
    ],
    equipo: [
      'Camilla rígida',
      'Botiquín ABC',
      'Oxígeno portátil',
      'Collarín y férulas',
      'DEA',
      'Radio',
    ],
  },
  'cruzroja-intensiva': {
    label: 'Ambulancia Cruz Roja Intensiva',
    descripcion: 'Ambulancia SVA de Cruz Roja Mexicana.',
    capacidad: '1 paciente crítico',
    personal: [
      { rango: 'Médico', rol: 'Médico de urgencias' },
      { rango: 'TUM-A',  rol: 'Técnico avanzado' },
      { rango: 'TUM-B',  rol: 'Conductor' },
    ],
    equipo: [
      'Monitor desfibrilador',
      'Ventilador de transporte',
      'Bomba de infusión',
      'Maletín ALS',
      'Carro de medicamentos',
      'Camilla hidráulica',
    ],
  },
  'convoy-sedena': {
    label: 'Convoy SEDENA Plan DN-III',
    descripcion: 'Convoy militar de apoyo a población civil.',
    capacidad: '1 oficial + 12 elementos',
    personal: [
      { rango: 'Capitán',  rol: 'Comandante de sección' },
      { rango: 'Teniente', rol: 'Subcomandante' },
      { rango: 'Sargento', rol: 'Jefe de pelotón' },
      { rango: 'Soldados (10)', rol: 'Apoyo, evacuación y seguridad' },
    ],
    equipo: [
      'Camión militar 2½ ton',
      'Equipo de despeje',
      'Hospital de campaña ligero',
      'Generadores',
      'Comunicaciones HF',
      'Raciones de campaña',
    ],
  },
  'ingenieros-sedena': {
    label: 'Ingenieros SEDENA',
    descripcion: 'Sección de ingenieros militares para remoción de escombros.',
    capacidad: '8 elementos + maquinaria',
    personal: [
      { rango: 'Mayor',    rol: 'Comandante de sección' },
      { rango: 'Teniente', rol: 'Subcomandante' },
      { rango: 'Sargento', rol: 'Operador maquinaria' },
      { rango: 'Soldados (5)', rol: 'Apoyo' },
    ],
    equipo: [
      'Retroexcavadora',
      'Compresores neumáticos',
      'Cortadoras pesadas',
      'Apuntalamientos metálicos',
      'Generador 30 kVA',
    ],
  },
  'marina-refuerzo': {
    label: 'Sección SEMAR Plan Marina',
    descripcion: 'Apoyo de SEMAR en operaciones urbanas y costeras.',
    capacidad: '10 elementos',
    personal: [
      { rango: 'Capitán',  rol: 'Comandante' },
      { rango: 'Teniente', rol: 'Subcomandante' },
      { rango: 'Marinos (8)', rol: 'Apoyo / búsqueda' },
    ],
    equipo: [
      'Lanchas inflables',
      'Equipo de buceo',
      'Equipo de despeje',
      'Comunicaciones HF',
    ],
  },
  'helicoptero-condor': {
    label: 'Helicóptero Cóndor SSC',
    descripcion: 'Helicóptero de seguridad ciudadana y evacuación médica.',
    capacidad: '4 ocupantes + 1 paciente en camilla',
    personal: [
      { rango: 'Piloto',    rol: 'Piloto al mando' },
      { rango: 'Co-piloto', rol: 'Operador' },
      { rango: 'TUM-A',     rol: 'Atención médica' },
    ],
    equipo: [
      'Camilla aérea',
      'Maletín ALS',
      'Cabrestante',
      'Cámara FLIR',
      'Reflectores',
    ],
  },
  'helicoptero-marina': {
    label: 'Helicóptero SEMAR',
    descripcion: 'Helicóptero MI-17 de la Marina para operaciones de rescate.',
    capacidad: '12 ocupantes',
    personal: [
      { rango: 'Capitán',   rol: 'Piloto' },
      { rango: 'Teniente',  rol: 'Co-piloto' },
      { rango: 'Rescatista', rol: 'Cabrestante' },
      { rango: 'Médico',     rol: 'Atención' },
    ],
    equipo: [
      'Cabrestante hidráulico',
      'Camilla aérea',
      'Equipo de buceo',
      'Botiquín avanzado',
    ],
  },
  'hospital-3er-nivel': {
    label: 'Hospital de 3er Nivel',
    descripcion: 'Centro hospitalario receptor con todas las especialidades.',
    capacidad: 'Múltiples camas censables; UCI; trauma center',
    hospitalCapacity: {
      camasCensables:   180,
      camasUCI:          24,
      quirofanos:         8,
      camasUrgencias:    30,
      helipuerto:       true,
      bancoSangre:      true,
      tomografia:       true,
      traumaCenter:     true,
      nivelAtencion:    'III',
    },
    personal: [
      { rango: 'Director',  rol: 'Dirección médica' },
      { rango: 'Médicos',   rol: 'Equipo de urgencias 24/7' },
      { rango: 'Enfermería', rol: 'Personal de turno' },
    ],
    equipo: [
      'Quirófanos',
      'Tomografía / Rayos X',
      'UCI / UCIN',
      'Banco de sangre',
      'Helipuerto',
    ],
  },
  'hospital-2do-nivel': {
    label: 'Hospital de 2º Nivel',
    descripcion: 'Hospital general de especialidades intermedias.',
    capacidad: 'Urgencias + hospitalización general',
    hospitalCapacity: {
      camasCensables:   90,
      camasUCI:          8,
      quirofanos:        4,
      camasUrgencias:   18,
      helipuerto:       false,
      bancoSangre:      true,
      tomografia:       false,
      traumaCenter:     false,
      nivelAtencion:    'II',
    },
    personal: [
      { rango: 'Director', rol: 'Dirección médica' },
      { rango: 'Médicos',  rol: 'Equipo de urgencias' },
    ],
    equipo: [
      'Urgencias',
      'Quirófano',
      'Rayos X',
      'Laboratorio clínico',
    ],
  },
  'hospital-1er-nivel': {
    label: 'Centro de Salud / 1er Nivel',
    descripcion: 'Centro de salud y atención primaria (no hospitalización mayor).',
    capacidad: 'Consulta externa + urgencias menores',
    hospitalCapacity: {
      camasCensables:   10,
      camasUCI:          0,
      quirofanos:        0,
      camasUrgencias:    4,
      helipuerto:       false,
      bancoSangre:      false,
      tomografia:       false,
      traumaCenter:     false,
      nivelAtencion:    'I',
    },
    personal: [
      { rango: 'Médico', rol: 'Médico de consulta externa' },
      { rango: 'Enf.',   rol: 'Enfermera responsable' },
    ],
    equipo: [
      'Consultorio médico',
      'Sala de urgencias menor',
      'Medicamentos básicos CAUSES',
    ],
  },
  'acv-fijo': {
    label: 'ACV Fijo (Área Concentración Víctimas)',
    descripcion: 'Punto de concentración y clasificación táctica de víctimas (START/SALT). Próximo al incidente.',
    capacidad: '30–50 víctimas simultáneas',
    acvCapacity: {
      capacidadTotal:   50,
      camillasDisp:     20,
      equipoTriage:     'START / SALT',
      color: {
        rojo:    10,  // inmediato
        amarillo: 15, // diferido
        verde:   20,  // menor
        negro:    5,  // expectante
      },
      ambulanciasEnlace: 3,
      coordMedica: true,
    },
    personal: [
      { rango: 'Médico',      rol: 'Coordinador médico ACV' },
      { rango: 'TUM-A',       rol: 'Triage officer' },
      { rango: 'TUM-B (x4)',  rol: 'Estabilización' },
      { rango: 'Enfermería',  rol: 'Soporte' },
    ],
    equipo: [
      'Sistema de etiquetas START (rojo/amarillo/verde/negro)',
      'Colchonetas y camillas de campaña',
      'Botiquines de trauma avanzado',
      'Generador + iluminación de área',
      'Tienda/carpa de triaje',
      'Radio P25 y megáfono',
    ],
  },
  'acv-avanzado': {
    label: 'Puesto Médico Avanzado (PMA)',
    descripcion: 'ACV avanzado con capacidad de estabilización e intervención pre-quirúrgica.',
    capacidad: '20 pacientes simultáneos en estabilización',
    acvCapacity: {
      capacidadTotal:   20,
      camillasDisp:     10,
      equipoTriage:     'SALT avanzado',
      color: {
        rojo:    8,
        amarillo: 8,
        verde:   10,
        negro:    4,
      },
      ambulanciasEnlace: 5,
      coordMedica: true,
      cirugiaDeCampaña: true,
    },
    personal: [
      { rango: 'Cirujano',   rol: 'Cirujano de campaña' },
      { rango: 'Médico x2',  rol: 'Estabilización' },
      { rango: 'Anestesista', rol: 'Soporte anestésico' },
      { rango: 'TUM-A x4',   rol: 'Triage y transporte' },
    ],
    equipo: [
      'Quirófano de campaña portátil',
      'Ventilador de transporte x2',
      'Desfibrilador manual x2',
      'Banco de sangre de campaña',
      'Generador 10 kVA',
      'Iluminación LED de área',
    ],
  },
}

export const getTemplate = (typeCode) => UNIT_TEMPLATES[typeCode] ?? null
